export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const GET_ALL_RECOMMENDATION = "GET_ALL_RECOMMENDATION";

export const GET_CHAIRS_BY_HALL = "GET_CHAIRS_BY_HALL";
export const GET_RESERVATED_CHAIRS_BY_HALL = "GET_RESERVATED_CHAIRS_BY_HALL";
export const ADD_SELECTED_SEAT = "ADD_SELECTED_SEAT";
export const DELETE_SELECTED_SEAT = "DELETE_SELECTED_SEAT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";